site_name: JokerPlus Documentation
site_description: Documentation for JokerPlus
site_author: Jokerplus
# site_url: https://joker5api231.com/jokerplus/jokerplusdocumentation/docs
site_url: https://localhost:7242/docs/
use_directory_urls: true

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - content.tooltips

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6

extra_css:
  - assets/stylesheets/custom.css

markdown_extensions:
  - material.extensions.preview:
        configurations:
          - targets:
              include:
                - reference/*
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.keys
  - footnotes
  - abbr
  - def_list
  - pymdownx.critic
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search


# extra:
#   consent:
#     title: Cookie consent
#     description: >
#       This page uses cookie

nav:
  - Home:
    - Introduction: index.md
    - Syntax Reference: code_examples.md
  - Authentication:
    - Overview: authentication/overview.md 
    - Encryption: authentication/encryption.md
  - API Endpoints:
    - On Boarding:
      - Overview: api/onboarding/onboarding.md
      - Login by Social App: api/onboarding/login_by_social_app.md
      - Login by Username: api/onboarding/login_by_username.md
      - Login by Pin: api/onboarding/login_by_pin.md
      - Register: api/onboarding/register.md
      - Check Username: api/onboarding/check_username.md
      - Username Suggestion: api/onboarding/username_suggestions.md
      - Verify Account For Reset Password: api/onboarding/verify_account_for_reset_password.md
      - Send Verify Code: api/onboarding/send_verify_code.md
      - Verify Code (Main): api/onboarding/verify_code_main.md
      - Verify Code (Local): api/onboarding/verify_code_local.md
      - Verify Email: api/onboarding/verify_email.md
      - Reset Password: api/onboarding/reset_password.md
      - Send Verify Code For Reset Pin: api/onboarding/send_verify_code_for_reset_pin.md
      - Reset Pin: api/onboarding/reset_pin.md
      - Get Interest List: api/onboarding/get_interest_list.md
      - Save Member Interest: api/onboarding/save_member_interest.md
      - Check Email: api/onboarding/check_email.md
      - Check Email Verification: api/onboarding/check_email_verification.md
      - Check Referral Code: api/onboarding/check_referral_code.md
      - Check Balance: api/onboarding/check_balance.md
      - Join Waitlist: api/onboarding/join_waitlist.md
      - Check Waitlist: api/onboarding/check_waitlist.md
      - Recover Username by email: api/onboarding/recover_username_by_email.md
      - Update Win Notification: api/onboarding/update_win_notification_status.md
    - Account Settings:
      - Overview: api/account_settings/account_settings.md
    - Security:
      - Overview: api/security/security.md
    - Wallet:
      - Overview: api/wallet/wallet.md
    - Lottery:
      - Overview: api/lottery/4d.md
    - Lucky Seven:
      - Overview: api/lucky_seven/lucky_seven.md
    - Chat:
      - Overview: api/chat/chat.md
    - Beta Mission:
      - Overview: api/beta_mission/beta_mission.md
    - Feedback:
      - Overview: api/feedback/feedback.md
    - Soccer:
      - Overview: api/soccer/soccer.md
      - Match Trend: api/soccer/get_match_trend.md
    - VIP Benefit:
      - Overview: api/vip/vip_benefit.md
    - Customer Service:
      - Overview: api/customer_service/customer_service.md
    - Slots:
      - Overview: api/slots/slots.md
    - Live Casino:
      - Overview: api/live_casino/live_casino.md
  - Reference:
    - Code Reference: reference/reference_codes.md
    - Glossary: reference/glossary.md
  - Change Log: changelog.md
