[project]
name = "jokerplusdocumentation"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "mkdocs-material>=9.7.0",
    "mkdocs-glightbox>=0.5.0",
]
